id: ideation
name: "Ideation"
question: "What possibilities are there? What could we do?"

description: |
  Techniques for generating new ideas, options, and creative
  solution approaches. Focus on quantity and creativity.

techniques:
  - brainstorming      # Classic, team, unfiltered
  - scamper            # Structured, apply to existing
  - mind-mapping       # Visual, associative, branching
  - reverse-thinking   # Aim for opposite for new perspectives
  - first-principles   # Radically rethink from fundamentals

triggers:
  - "We need new features"
  - "How could we solve X?"
  - "What are our options?"
  - "Creative block"
  - "Fill the backlog"

examples:
  - "What features could we build?"
  - "How can we improve the UX?"
  - "What would be an alternative to X?"
  - "How do others do it?"

recommended_start: brainstorming
recommended_start_reason: "Low barrier to entry, always works"

escalation: |
  If brainstorming stagnates, use SCAMPER for structured
  transformations or Reverse Thinking for perspective shift.
