id: teamwork
name: "Teamwork"
question: "How do we work together? Who does what?"

description: |
  Techniques for effective collaboration, participation of all,
  and joint decision-making in a team.

techniques:
  - round-robin          # Everyone gets a turn
  - brainstorming        # Generate ideas together
  - dot-voting           # Prioritize democratically
  - retrospective        # Reflect together
  - pre-mortem           # Identify risks together
  - fishbone-diagram     # Analyze together
  - stakeholder-mapping  # Clarify roles
  - code-walkthrough     # Understand code together
  - six-thinking-hats    # Structured discussion

triggers:
  - "Team meeting"
  - "We need to agree"
  - "Introverts are being drowned out"
  - "Decision with commitment"
  - "Conflicts in team"

examples:
  - "How do we distribute the work?"
  - "What do we prioritize?"
  - "How do we resolve this conflict?"
  - "How can everyone contribute?"

recommended_start: round-robin
recommended_start_reason: "Ensures EVERYONE is heard before discussion"

escalation: |
  In case of conflict: First Round Robin for all perspectives,
  then Six Thinking Hats for structured discussion.
