id: root-cause-analysis
name: "Root Cause Analysis"
question: "Why did this happen? What is the root of the problem?"

description: |
  Techniques for systematically identifying the actual cause
  of a problem, rather than just treating symptoms.

techniques:
  - five-whys              # Quick, iterative, good for simple chains
  - systematic-debugging   # 4-phase process, enforced by loop_breaker hook
  - fishbone-diagram       # Visual, categorized, good for complex systems
  - after-action-review    # Structured reflection after event
  - socratic-questioning   # Uncover assumptions through questions

triggers:
  - "Error occurs repeatedly"
  - "Obvious solution didn't help"
  - "Symptom vs. cause unclear"
  - "Bug found, but why?"
  - "Incident happened"

examples:
  - "Why is the app crashing?"
  - "Why are the tests slow?"
  - "Why did the deployment fail?"
  - "Why is the customer unhappy?"

recommended_start: five-whys
recommended_start_reason: "Quick, needs no tools, works solo"

escalation: |
  If Five Whys doesn't lead to the cause (e.g., multiple causes suspected),
  switch to Fishbone Diagram for systematic categorization.
