id: self-reflection
name: "Self-Reflection"
question: "What have I learned? What am I doing well/poorly?"

description: |
  Techniques for personal reflection on one's own actions,
  learning, and improvement. Core of continuous growth.

techniques:
  - retrospective         # Structured team reflection
  - after-action-review   # Immediately after event
  - five-whys             # Why did I act that way?
  - rubber-duck-debugging # Verbalize own thoughts
  - socratic-questioning  # Question own assumptions
  - code-walkthrough      # Review own code

triggers:
  - "That went wrong"
  - "That went well - why?"
  - "What have I learned?"
  - "How can I improve?"
  - "Sprint/project completed"

examples:
  - "Why did I make this mistake?"
  - "What would I do differently next time?"
  - "What worked well today?"
  - "Where am I stuck and why?"

recommended_start: after-action-review
recommended_start_reason: "Structured and timely, before details are forgotten"

escalation: |
  For deeper reflection: Apply Socratic Questioning to own assumptions,
  or Five Whys to own behavioral patterns.
